name: Latest blog post workflow
on:
  workflow_dispatch:
  schedule:
    # Runs every hour
    - cron: "0 * * * *"
  

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBE
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCnQzZNPePG3EZMj7Qg3D0Sw"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "julio.arruda@outlook.com"   

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: YOUTUBEEN
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCrZPzM0WazlHyAheVH9132Q"
          custom_tags: "channelId/yt:channelId/,videoId/yt:videoId/"
          date_format: "mmm d, yyyy"
          template: '<table><tr><td><a href="$url"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg"></a></td>$newline<td><a href="$url">$title</a><br/>$date</td></tr></table>$newline'
          committer_email: "julio.arruda@outlook.com"   
          
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: MEETUP
          feed_list: "http://feeds.feedburner.com/Events-netVale"
          committer_email: "julio.arruda@outlook.com" 

